### ISSUE TITLE
Display banner like "Explore - Logs", to encourage user to provide feedback

### ISSUE THREAD

**Issue by simonswine** [grafana/explore-profiles#66]
Explore - Logs, shows this banner and also the "preview" icon and give feedback link:

I think we should copy it and have our own Google Form
 
![image](https://github.com/user-attachments/assets/971955d4-d31e-4d01-81dc-b6c7c90e91b0)

**Comment by AndrejKiri** [comment]
@simonswine I think this is a good idea. 👍 

Regarding the banner, since the vertical space is pretty scarce, I would suggest a shorter text in the panel. Perhaps something like this: `Explore profiles app is in active development. Please expect things to change.`

Regarding the _Give feedback_ link, I would love to help with creating a questionnaire and connecting the responses to Grafana dashboard ([here](https://bi.grafana-ops.net/d/ddiud1hg7uc5cc/docs-user-satisfaction?viewPanel=panel-31) is an example of a panel with survey responses). Please, let me know once this becomes relevant.

**Comment by AndrejKiri** [comment]
I created the survey in Qualtrics, in case we decide to use it. 

Here is a url to link users to: `https://grafana.qualtrics.com/jfe/form/SV_6Gav4IUU6jcYfd4`. Here is [a link](https://bi.grafana-ops.net/d/cduwees42hddse/product-feedback-surveys-in-qualtrics?from=2024-09-13T04:25:11.676Z&to=2024-09-13T10:25:11.676Z&timezone=utc&tab=queries) to the Grafana dashboard where the data will be displayed. 

In Slack, @matryer also shared [the code for the Give Feedback Button](https://github.com/grafana/explore-logs/blob/main/src/Components/IndexScene/GiveFeedbackButton.tsx).
